"""Create blog posts and readlists models

Revision ID: 197af321add0
Revises: ed0cf1f3c787
Create Date: 2025-12-09 18:30:24.350451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197af321add0'
down_revision = 'ed0cf1f3c787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('posts_readlists',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('readlist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['readlist_id'], ['readlist.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'readlist_id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('excerpt', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['slug'])
        batch_op.create_unique_constraint(None, ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('excerpt')
        batch_op.drop_column('slug')

    op.drop_table('posts_readlists')
    op.drop_table('readlist')
    # ### end Alembic commands ###
