"""Add description to work experience

Revision ID: 7cd5a2c77888
Revises: 
Create Date: 2025-12-09 15:45:40.602441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd5a2c77888'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_experience', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
