"""Add is_sold to Product model

Revision ID: 8a65d6e40fa2
Revises: c6fb8ba2d1fb
Create Date: 2025-12-11 19:29:11.409143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a65d6e40fa2'
down_revision = 'c6fb8ba2d1fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sold', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_sold')

    # ### end Alembic commands ###
