"""Change post content to MEDIUMTEXT

Revision ID: abf2ffa28c6a
Revises: f01c597e00d5
Create Date: 2025-12-10 09:45:33.978316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abf2ffa28c6a'
down_revision = 'f01c597e00d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
