"""Add post ordering to readlists

Revision ID: def9924df9d0
Revises: abf2ffa28c6a
Create Date: 2025-12-10 14:20:48.568302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'def9924df9d0'
down_revision = 'abf2ffa28c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('posts_readlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts_readlists', schema=None) as batch_op:
        batch_op.drop_column('post_order')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
