"""Add case study to project

Revision ID: eb68b663df83
Revises: c4be152f54a6
Create Date: 2025-12-12 21:46:35.036747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb68b663df83'
down_revision = 'c4be152f54a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_study_url', sa.String(length=200), nullable=True))
        batch_op.drop_column('collaborators')
        batch_op.drop_column('cost')
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('cost', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('collaborators', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('case_study_url')

    # ### end Alembic commands ###
