"""Enhance project model with new fields

Revision ID: ed0cf1f3c787
Revises: 7cd5a2c77888
Create Date: 2025-12-09 16:37:59.675864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0cf1f3c787'
down_revision = '7cd5a2c77888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tools', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('collaborators', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('order')
        batch_op.drop_column('collaborators')
        batch_op.drop_column('cost')
        batch_op.drop_column('duration')
        batch_op.drop_column('video_url')
        batch_op.drop_column('tools')

    # ### end Alembic commands ###
