"""added the product galley

Revision ID: fb63c4f8ee8c
Revises: 665f5e60845d
Create Date: 2025-12-11 10:57:35.105465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb63c4f8ee8c'
down_revision = '665f5e60845d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('subtitle', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('features', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gallery_images', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('gallery_images')
        batch_op.drop_column('features')
        batch_op.drop_column('subtitle')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
