"""Restore cost and collaborators, add role to Project

Revision ID: fdb72b95cf7e
Revises: eb68b663df83
Create Date: 2025-12-12 22:08:43.679910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb72b95cf7e'
down_revision = 'eb68b663df83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('collaborators', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('collaborators')
        batch_op.drop_column('cost')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
